# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-cplusplus-container-images
  include:
    - dobi.yaml
    - version.yaml
    - builder/dobi.yaml
    - runtime/dobi.yaml
