# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-cplusplus-container-images
  include:
    - dobi.yaml
    - version.yaml
    - builder/dobi.yaml
    - runtime/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - bb-cplusplus-container-images-version
  annotations:
    description: "-> generate version informations (auto called by dobi.sh)"

alias=build:
  tasks:
    - bb-cplusplus-container-images-build
  annotations:
    description: "-> build all content"

alias=deploy:
  tasks:
    - bb-cplusplus-container-images-deploy
  annotations:
    description: "-> deploy all content"
