resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
      username: ((registry_user))
      password: ((registry_password))
      tag: 1.0.19

resources:
  - name: source
    type: git
    source:
      uri: ((git_source))
      private_key: ((privatekey))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))

  - name: image-bb-gitversion-tool
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      username: ((registry_user))
      password: ((registry_password))
      tag: ((bb_gitversion_version))

  - name: image-((bb_image_pref))-builder
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-builder
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))

  - name: image-((bb_image_pref))-runtime-x86_64
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-runtime-x86_64
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_image_pref))-runtime-x86_64-dev
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-runtime-x86_64-dev
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_image_pref))-runtime-aarch64
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-runtime-aarch64
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_image_pref))-runtime-aarch64-dev
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-runtime-aarch64-dev
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_image_pref))-runtime-armv7hf
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-runtime-armv7hf
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))
  - name: image-((bb_image_pref))-runtime-armv7hf-dev
    type: docker-image
    source:
      repository: ((bb_docker_namespace))/((bb_image_pref))-runtime-armv7hf-dev
      username: ((registry_user))
      password: ((registry_password))
      insecure_registries: ((bb_insecure_registries))

  - name: send-an-email
    type: email
    source:
      smtp:
        host: ((email_smtp_host_url))
        port: ((email_smtp_port))
        anonymous: ((email_smtp_anonymous))
        username: ((email_smtp_user))
        password: ((email_smtp_pw))
        skip_ssl_validation: ((email_smtp_skip_ssl_validation))
        ca_cert: ((email_smtp_ca_cert))
        host_origin: ((email_smtp_host_origin))
        login_auth: ((email_smtp_login_auth))
      from:  ((email_from))
      to: ((email_to))

jobs:
  - name: build-and-deploy-((bb_name))
    public: true
    on_failure:
      put: send-an-email
      params:
        subject_text: "ci ${BUILD_PIPELINE_NAME}: build ${BUILD_ID} failed!"
        body_text: |
          Oh no!
          Build ID: "${BUILD_ID}"
          Build Name: "${BUILD_NAME}"
          Build Job Name: "${BUILD_JOB_NAME}"
          Build Pipeline Name: "${BUILD_PIPELINE_NAME}"
          ATC External URL: "${ATC_EXTERNAL_URL}"
    on_success:
      put: send-an-email
      params:
        subject_text: "ci ${BUILD_PIPELINE_NAME}: build ${BUILD_ID} successfully finished"
        body_text: |
          Yeah!
          Build ID: "${BUILD_ID}"
          Build Name: "${BUILD_NAME}"
          Build Job Name: "${BUILD_JOB_NAME}"
          Build Pipeline Name: "${BUILD_PIPELINE_NAME}"
          ATC External URL: "${ATC_EXTERNAL_URL}"
    plan:
      - in_parallel:
          - get: source
            trigger: true
          - get: image-bb-gitversion-tool

      - task: generate-version
        image: image-bb-gitversion-tool
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: gitversion
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                entrypoint.sh
          params:
            GIT_PATH: source
            GEN_PATH: gitversion
            GIT_BRANCH: "((git_branch))"
            DEFAULT_BRANCH: "((default_branch))"
            VERBOSE: 1

      - in_parallel:
          - put: image-((bb_image_pref))-builder
            params:
              build: source/builder
              dockerfile: source/builder/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
          - put: image-((bb_image_pref))-runtime-x86_64
            params:
              build: source/runtime
              build_args:
                ARCH: "amd64"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
          - put: image-((bb_image_pref))-runtime-x86_64-dev
            params:
              build: source/runtime
              build_args:
                ARCH: "amd64"
                DEV: "1"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
          - put: image-((bb_image_pref))-runtime-aarch64
            params:
              build: source/runtime
              build_args:
                ARCH: "arm64v8"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
          - put: image-((bb_image_pref))-runtime-aarch64-dev
            params:
              build: source/runtime
              build_args:
                ARCH: "arm64v8"
                DEV: "1"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
          - put: image-((bb_image_pref))-runtime-armv7hf
            params:
              build: source/runtime
              build_args:
                ARCH: "arm32v7"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
          - put: image-((bb_image_pref))-runtime-armv7hf-dev
            params:
              build: source/runtime
              build_args:
                ARCH: "arm32v7"
                DEV: "1"
              dockerfile: source/runtime/Dockerfile
              tag_as_latest: ((bb_release_as_latest))
              tag_file: gitversion/plain/BranchVersionDockerLabel
